### ISSUE TITLE
options not being read in correctly

### ISSUE THREAD

**Issue by Caesurus** [vlad-s/hcpxread#1]
Using the application on windows I see the following when making a selection:

`time="2020-08-02T15:49:13-04:00" level=error msg="Error scanning input: unexpected newline"`

**Comment by vlad-s** [comment]
Thanks for letting me know. Unfortunately I don't have a Windows machine ready to try to debug and spinning up a VM will take some time that I don't currently have. I reckon that the issue resides in reading `os.Stdin` [here](https://github.com/vlad-s/hcpxread/blob/2fba4ceeef579659c62a060c74f9fc9c51ed8ce3/main.go#L98), probably related to Windows using `\r\n` instead of `\n` as line delimiters. Very possible to be related to https://github.com/golang/go/issues/23562. Sorry, but I can't work on this right now. If you want to use this, please try to run it inside WSL, it should work over there.

**Comment by Caesurus** [comment]
Yeah no problem. When I originally submitted the issue I was intending to go fix it myself and issue a PR. Then I got distracted with other things and I only just got to doing it. No big deal if you don't take it, just figured I'd have it there in case others encounter the same thing. Thanks
